<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="4SHISH" failures="1" tests="3" name="Test" time="350.88" errors="0" timestamp="2023-11-18T10:34:45 IST">
  <testcase classname="sanity.liberty" name="main" time="86.271"/>
  <testcase classname="sanity.sbi" name="main" time="117.02"/>
  <testcase classname="sanity.usgi" name="main" time="147.459">
    <failure type="java.io.FileNotFoundException" message=".\testdata\usgi.xlsx (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: .\testdata\usgi.xlsx (The process cannot access the file because it is being used by another process)
at java.base/java.io.FileOutputStream.open0(Native Method)
at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:236)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
at sanity.usgi.main(usgi.java:296)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- main -->
</testsuite> <!-- Test -->
